#!/bin/python3
#   Programa que automaticamente altera os arquivos da
#   pasta de Download para as respectivas pastas de destino.
#   Autor: Arthur Novais
#


from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
from pathlib import Path
from util import in_app_path
import configparser import ConfigParser
import time
import json
import os

class MyHandler(FileSystemEventHandler):
    #Caso ocorra modificacao
    def on_modified(self, event):
        #Para cada arquivo na pasta de origem
        for arquivo in os.listdir(pastaOrigem):
            #Salvo o caminho do arquivo
            src = pastaOrigem + "/" + arquivo
            #salva o tamanho do arquivo atual
            tamanhoArquivo = os.path.getsize(src)
            #Salvo o novo caminho do arquivo
            novoDestino = src;
            #Espera um segundo
            time.sleep(1)
            if os.path.isfile(src):
                #Enquanto o arquivo estiver mudando o valor(sendo baixado/transferido) espere

                while (tamanhoArquivo != os.path.getsize(src)):
                    tamanhoArquivo = os.path.getsize(src)
                    time.sleep(1)

                if arquivo.lower().endswith(('.png', '.jpg', '.jpeg')):
                    novoDestino = pastaImagem
                elif arquivo.lower().endswith('.deb'):
                    novoDestino = pastaDeb
                elif arquivo.lower().endswith(('.mobi', '.epub')):
                    novoDestino = pastaLivro
                elif arquivo.lower().endswith('.pdf'):
                    novoDestino = pastaPdf
                elif arquivo.lower().endswith('.mp3'):
                    novoDestino = pastaMusica
                elif arquivo.lower().endswith(('.gz', '.tar', '.zip', 'tgz')):
                    novoDestino = pastaCompactado
                elif arquivo.lower().endswith(('.webm', '.mp4', '.avi', '.wmv', '.mov', 'flv')):
                    novoDestino = pastaVideo
                else:
                    novoDestino = pastaDocumento
                #Salvo o arquivo no novo caminho
                print('Enviando '+ arquivo+ ' para a pasta ' + novoDestino)
                os.rename(src,novoDestino + "/" + arquivo)

class Config:
    """
        Class that loads the values used on the program
    """
    def loadInit():
        file = in_app_path("./auto.init")
        config = ConfigParser()
        config.read(file)

        len_args = {}

       for section in list(config['directory']
                len_args[section] = config['directory'][section])

       for section in list(config['extension']
                len_args[section] = config['extension'][section])

        return len_args 

class Log:
    """
        Class that save all the 
    """

#Pasta de origem
pastaOrigem = '/home/arthur/Downloads'
pastaImagem = '/home/arthur/Pictures'
pastaDocumento = '/home/arthur/Documents'
pastaMusica = '/home/arthur/Music'
pastaVideo = '/home/arthur/Videos'

pastaDeb = '/home/arthur/Downloads/deb'
pastaPdf = '/home/arthur/Documents/PDF'
pastaLivro = '/home/arthur/Documents/Livros'
pastaCompactado = '/home/arthur/Downloads/Compactado'

#Evento observando se tem alteração na pasta de Origem
event_handler = MyHandler()
observer = Observer()
observer.schedule(event_handler, pastaOrigem, recursive=True)
observer.start()

try:
    while True:
        #Tempo até a próxima verificação
        time.sleep(10)
except KeyboardInterrupt:
    observer.stop()
observer.join
